IE104_SC/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic.base import TemplateView
import product.views as productV, news.views as newsV, accounts.views as accountV
import brand.views as Brand

# Media and Ckeditor
from django.conf.urls.static import static
from IE104_SC import settings
import os

from django.contrib.auth import views as authV

from django.contrib.sitemaps.views import sitemap
from sitemaps import ProductSitemap, NewsSitemap, StaticSitemap

# Rich Text Field

# Sitemaps
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import views
from django.views.decorators.cache import cache_page


sitemaps = {
    'product': ProductSitemap,
    'news': NewsSitemap,
    'static': StaticSitemap,
}


urlpatterns = [
    path('', productV.Homepage, name='homepage'),
    path('admin/', admin.site.urls),
    path('product/', include('product.urls')), 
    path('news/', include('news.urls')),
    path('brand/', include('brand.urls')),

    # Authentication
    path('accounts/', include('django.contrib.auth.urls')),
    path('account/', include('accounts.urls')),
    # path('logout/', accountV.LogoutView.as_view(template_name="accounts/logout.html"), name='logout'),
    path('register/', accountV.registration, name='register'),
    path('login/', authV.LoginView.as_view(template_name="accounts/login.html"), name='login'),
    path('change_password/',accountV.change_password, name='change_password'),

    # Others
    path('search/', productV.SearchResults.as_view(), name='search_results'),
    path('recommend/', productV.Recommend, name='recommend'),
    path('about/', accountV.aboutView, name='about'),

    # rich text field
    path('djrichtextfield/', include('djrichtextfield.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    # sitemap
    path('sitemap.xml', views.index, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('site-<section>.xml', views.sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path("robots.txt", TemplateView.as_view(template_name="accounts/robots.txt", content_type="text/plain")),

    re_path('djga/', include('google_analytics.urls')),
]

# if settings.dev.DEBUG:
#     urlpatterns += [re_path('djga/', include('google_analytics.urls')),]

# if settings.DEBUG:
#    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.base.MEDIA_URL, document_root=settings.base.MEDIA_ROOT)

news/urls.py
from django.urls import path
from .views import NewsListView, NewsDetail

app_name = 'news'

urlpatterns = [
    path('', NewsListView.as_view(), name='news-list'),
    path('<int:news_id>/<str:slug>/', NewsDetail, name='news-detail')   
]

product/urls.py
from django.urls import path, include
from . import views

app_name = 'product'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='product-list'),
    path('<int:product_id>/<slug:slug>/', views.productDetail, name='product-detail'),
]

product/models.py
from django.db import models
from django.utils import timezone
import datetime
from django.contrib.auth.models import User
from django.conf import settings
from django.urls import reverse

from brand.models import Brand

from django.template.defaultfilters import slugify

# Multiple Choice Field
from multiselectfield import MultiSelectField
# Rich Text Field
# from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
# from djrichtextfield.models import RichTextField
#pip install Pillow for image import

# CK Editor
from ckeditor.fields import RichTextField

# Create your models here.

SKINCOND_CHOICE = (
    ('SEN', 'Sensitive Skin'),
    ('ACNE', 'Acne Skin'), 
    ('AGE', 'Aging Skin'),
    ('DULL', 'Dull Skin'),
    ('FREC', 'Freckles'),
)

CATEGORY_CHOICE = (
    ('MAKEUP_RM', 'Makeup Remover'),
    ('CLEANSE', 'Cleanser'),
    ('TONER', 'Toner'),
    ('SERUM', 'Serum'),
    ('MOIST', 'Moisturizer'),
    ('LOTION', 'Lotion'),
    ('MASK', 'Mask'),
    ('EYE', 'Eye Care'),
    ('SUN', 'Sun Care'),
    ('EXFOL', 'Exfoliators'),
    ('LIP', 'Lip Treatment'),
    ('MIST', 'Mist Spray'),
    ('OIL', 'Oil Moisturizing'),
    ('PERFUME', 'Perfume'),
    ('BODY', 'Body Care'),
    ('HAIR', 'Hair Care'),
)

SKINTYPE_CHOICE = (
    ('DRY', 'Dry Skin'), 
    ('OIL', 'Oily Skin'),
    ('COMBI', 'Combination Skin'),
    ('NORM', 'Normal Skin'),
)


class Product(models.Model):
    # Ten spham
    product_name = models.CharField(max_length=80, blank=False, null=False)

    #ten hang KEY 3 CHU DAU
    brand = models.ForeignKey('brand.Brand', on_delete=models.CASCADE)

    #tom tat spham
    summary = models.TextField(max_length=300, blank=False, null=False)

    # Giai thich ve spham
    #description = RichTextField()
    description = RichTextUploadingField(blank=True, null=True)

    #dung tich san pham
    product_size_in_ml = models.IntegerField(default=0, null=False) 

    #hinh minh hoa spham
    product_img = models.ImageField(upload_to='product/images/')

    # Gia spham
    price = models.CharField(default=0, max_length=7)

    # Spham phu hop voi loai da nao (da dau, da kho, v.v.)
    skinType = MultiSelectField(choices=SKINTYPE_CHOICE, null=True, blank=True)

    # Spham phu hop voi tinh trang da nao (bi mun, lao hoa, v.v.)
    skinCondition = MultiSelectField(choices=SKINCOND_CHOICE, null=True, blank=True)

    # Loai san pham: SRM, Toner, v.v.
    category = models.CharField(max_length=10, choices=CATEGORY_CHOICE, blank=True, null=True)

    # Binh chon yeu/ghet spham
    vote_down = models.IntegerField(default=0)
    vote_up = models.IntegerField(default=0)

    #slugField for endpoint
    slug = models.SlugField(max_length=40, unique=True)

    def __str__(self):
        return str(self.product_name)

    def get_absolute_url(self):
        slug = slugify(self.product_name)
        return reverse('product:product-detail', args=[str(self.id), slug])
        #return reverse('product:product-detail', args=[str(self.id)])

    def slug(self):
        return slugify(self.product_name)

class Comment(models.Model):
    #comment thuoc product nao
    product = models.ForeignKey('Product', on_delete=models.CASCADE) 

    #comment cua user nao
    # owner_comment = models.ForeignKey(User, on_delete=models.CASCADE)
    owner_comment = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    #Tua de cua comment
    title = models.CharField(max_length=255, blank=True, null=True)

    #Noi dung comment
    content = models.TextField()
    #thoi gian dang bai
    pub_date = models.DateTimeField(auto_now_add=True)
    
    # Binh chon yeu/ghet binh luan
    vote_down = models.IntegerField(default=0)
    vote_up = models.IntegerField(default=0)

    def __str__(self):
        return str(self.title)

product/forms.py
from django import forms
from .models import Comment

class pushCommentForms(forms.ModelForm):
    # product = forms.CharField(widget=forms.HiddenInput())
    # owner_comment = forms.CharField(widget=forms.HiddenInput())
    def __init__(self, *args, **kwargs):
        self.owner_comment = kwargs.pop('owner_comment', None)
        self.product = kwargs.pop('product', None)
        super().__init__(*args, **kwargs)

    def save(self, commit=True):
        comment = super().save(commit=False)
        comment.owner_comment = self.owner_comment
        comment.product = self.product
        comment.save()

    class Meta:
        model = Comment
        fields = ('content', )

product/views.py
from django import template
from django.http.response import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404

# views related
from django.views import generic
from . import views
from .models import Product
from django.template import loader

#class-based views
from django.views import generic

#search engine
from django.db.models import Q, query

#simple search ussing q
from django.db.models import Q

# import models
from .models import Product, Comment
from brand.models import Brand
from news.models import News
from django.contrib.auth.models import User

from .forms import pushCommentForms
from .filters import ProductFilter
# Create your views here.

# Home page queries
def Homepage(request):
    """ Products """
    productsLength = len(Product.objects.all())
    products = []
    for p in range(productsLength-8, productsLength, 4):
        products.append(Product.objects.all()[p:p+4])
    """ News """

    news = []
    for n in range(0, 8, 4):
        news.append(News.objects.order_by('-pub_date')[n: n+4])
    """ Brand """
    brands = []
    for b in range(0, 8, 4):
        brands.append(Brand.objects.filter(brandCategory__contains='TREN')[b: b+4])

    context = {
        'productList': products,
        'newsList': news,
        'brandList': brands,
    }

    return render(request, 'product/base_home.html', context)

def navbarQueries(request):
    # Brand Navigation
    trendBrand = Brand.objects.filter(brandCategory__contains="TREN")
    highendBrand = Brand.objects.filter(brandCategory__contains="HIGH")
    drugstoreBrand = Brand.objects.filter(brandCategory__contains="DRUG")

    # Product Navigation

    context_nav = {
        'trending': trendBrand,
        'highend': highendBrand,
        'drugstore': drugstoreBrand,
    }
    loader.get_template('product/base.html')
    return HttpResponse(template.render(context_nav, request))
    # return render(request, 'product/base.html', context_nav)

# Search toolbar
class SearchResults(generic.ListView):
    model = Product
    template_name = 'product/base_results.html'

    def get_queryset(self):
        query = self.request.GET.get('q')
        return Product.objects.filter(
            Q(product_name__icontains=query) |
            Q(description__icontains=query) |
            Q(brand__branding_name__icontains=query)
        )

""" Print all products """
class ProductListView(generic.ListView):
    model = Product
    template_name = 'product/base_productList.html'
    context_object_name = 'product_list'
    paginate_by = 12

    def get_queryset(self):
        return Product.objects.order_by("product_name")

""" Print product details """
def productDetail(request, product_id, slug):
    #get product id
    productD = Product.objects.get(pk=product_id)

    # read all related comment in product
    comments = Comment.objects.all() 
    productComment = []
    for comment in comments:
        if comment.product_id == product_id:
            productComment.append(comment)

    # Add new comment
    commentForm = pushCommentForms()
    message  = ''
    if request.method == 'POST':
        commentForm = pushCommentForms(request.POST, owner_comment=request.user, product=productD)
        if commentForm.is_valid():
            commentForm.save()
            message = 'Push comment succeed.'
            return redirect('product:product-detail', product_id, slug)
        else:
            commentForm = pushCommentForms()
            message = 'Push comment failed.'

    context = {
        'product': productD, 
        'comments': productComment,
        'new_comment': commentForm,
        'message': message,
    }
    return render(request, 'product/base_productDetail.html', context)

# Recommend product
def Recommend(request):
    if request.method == 'GET':
        removerFilter = ProductFilter(request.GET, queryset=Product.objects.filter(category="MAKEUP_RM"))
        cleanserFilter = ProductFilter(request.GET, queryset=Product.objects.filter(category="CLEANSE"))
        lotionFilter = ProductFilter(request.GET, queryset=Product.objects.filter(category="LOTION"))
        moistFilter = ProductFilter(request.GET, queryset=Product.objects.filter(category="MOIST"))
        sunFilter = ProductFilter(request.GET, queryset=Product.objects.filter(category="SUN")) 

        filterForm = ProductFilter(request.GET, queryset=Product.objects.all())
                
        context = {
            'filterForm': filterForm,
            'removerQ': removerFilter.qs,
            'cleanserQ': cleanserFilter.qs,
            'lotionQ': lotionFilter.qs,
            'moistQ': moistFilter.qs,
            'sunscreenQ': sunFilter.qs,
        }
    
    return render(request, 'product/base_recommend.html', context)

product/templates/product/base_productDetail.html
{% extends 'product/base.html' %}

{% load static %}

{% block title %}{{ product }} | {{ product.brand.branding_name }} | {% endblock title %}
{% block header %}
	<link type="text/css" rel="stylesheet" href="{% static 'product/css/productDetail.css' %}">
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700" rel="stylesheet">
	<link href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css"/>
	<!-- <script type="text/javascript" src="js/jquery-1.10.2.min.js"></script> -->
	<script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>
	<!-- <script src="//code.jquery.com/jquery-1.11.1.min.js"></script> -->
	<script src="https://code.iconify.design/1/1.0.7/iconify.min.js"></script>
	<!-- comment -->
	<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
	<link rel="stylesheet" type="text/css" href="https://www.shieldui.com/shared/components/latest/css/light-glow/all.min.css" />

	<!--Meta data -->
	<!--Meta OpenGraph-->
	<meta name="og:site_name" content="beautifME beautifme" />
	<meta name="og:description" content="{{ product.summary }}" />
	<meta name="og:title" content="{{ product }} | {{ product.brand.branding_name }} | beautifME gợi ý sản phẩm dưỡng da"/>
	<meta name="og:url" content="https://www.beautifme.com/product/{{ product.id }}/{{ product.slug }}/"/>
	<meta name="og:img" content="{{ product.product_img.url }}"/>
	<meta name="og:type" content="website"/>
	<!--Meta keywords-->
	<meta name="keywords" content="highend, high-end, high end, skincare, skin care"/>
    <meta name="keywords" content="blemish, discoloration, dermatologist, recommend, Cruelty-free, Non-irritating, sensitive, dark spots, dullness, uneven skin" />
    <meta name="keywords" content="AHA, vitamin C"/>
    <meta name="keywords" content="oily, dry, combination, acne prone, normal skin, aging skin, 30s, 20s, wrinkle, anti-aging" />
	<!--end Meta keywords-->
	<meta name="description" content="{{ product.summary }}"/>
	<meta name="product_article_id" content="{{ product.id }}" />
    <meta charset="UTF-8"/>
	<!--end Meta data-->
{% endblock header %}


{% block content %}
	<ul class="breadcrumb">
		<li><a href="{% url 'homepage' %}">Home</a></li>
		<li><a href="{% url 'product:product-list' %}">Products</a></li>
		<li>{{ product.product_name }}</li>
	</ul>
    <div class="container">
		<div class="card">
			<div class="container-fliud">
				<div class="wrapper row">
					<div class="columnImg">
						<div class="detailImg">
							<div class="detailImg" id="pic-1">
								<img src="{{ product.product_img.url }}" class="main-productImg" alt="{{ product.product_name}}-{{ product.brand.branding_name}}-beautifme" />
							</div>
						</div>
					</div>
					<div class="columnDetail">
						<h4 class="h4"><a href="/brand/{{ product.brand.id }}/{{ product.brand.slug }}/">{{ product.brand.branding_name }}</a></h4>
						<h1 class="product-title">{{ product.product_name }}</h1>
						<div class="rating">
							<div class="stars">
								<span class="iconify" data-icon="ant-design:like-filled" data-inline="false"
									style="color: #a75535; height: 30px; width: 70px;"></span>
								<span class="iconify" data-icon="ant-design:dislike-filled" data-inline="false"
									style="color: #a75535; height: 30px; width: 50px;"></span>
							</div>
							<div class="stars">
								<span class="iconify" style="width: 80px; padding-left: 30px; ">{{ product.vote_up }}</span>
								<span class="iconify">{{ product.vote_down }}</span>
							</div>
						</div>
						<p class="product-description">{{ product.summary }}</p>
						<h4 class="price">Price: <span>${{ product.price }}</span></h4>
						</p>
						<h5 class="sizes">Category:
							<span class="size" data-toggle="tooltip" title="small">{{ product.get_category_display }}</span>
						</h5>
						<h5 class="sizes">Sizes:
							<span class="size" data-toggle="tooltip" title="small">{{ product.product_size_in_ml }} ml</span>
						</h5>
						<h5 class="sizes">Skin type:
							<span class="size" data-toggle="tooltip" title="small">{{ product.skinType }}</span>
						</h5>
						<h5 class="sizes">Skin condition:
							<span class="size" data-toggle="tooltip" title="small">{{ product.skinCondition }}</span>
						</h5>

					</div>
				</div>
			</div>
		</div>
		<div class="tabs_div">
			<ul>
				<li>Description</li>
			</ul>
			<div>
				{{ product.description | safe }}
			</div>
		</div>
		
		<h1>Comment</h1>
		{% if user.is_authenticated %}
		<div class="row">
			<div class="col-lg-12">
				<div class="widget-area no-padding blank">
					<div class="status-upload">
						<form method="POST">
							{% csrf_token %}
							{{ new_comment.content }}
							<button type="submit" class="btn btn-success green"><i class="fa fa-share"></i> Share</button>
						</form>
						<div>
							{{ message }}
						</div>
					</div><!-- Status Upload  -->
				</div><!-- Widget Area -->
			</div>
		</div>
		{% else %}
		<p class="noti">You're not logged in. Click here to <a href="{% url 'login' %}?next={{ request.path }}">Login</a></p>
		{% endif %}
		<!-- Comment -->
		<div class="container bootdey">
			<div class="col-md-12 bootstrap snippets">
				<div class="panel">
					<div class="panel-body">
						<!-- Newsfeed Content -->
						<!--===================================================-->
                        {% for comment in comments %}
						<div class="media-block">
							<div class="media-left" href="#"><img class="img-circle img-sm" alt="Profile Picture"
									src="https://bootdey.com/img/Content/avatar/avatar1.png"></div>
                              
                                <div class="media-body">
                                    <div class="mar-btm">
                                        <p class="btn-link text-semibold media-heading box-inline">{{ comment.owner_comment }}</p>
                                        <p class="text-muted text-sm"><i class="fa fa-mobile fa-lg"></i> {{ comment.pub_date }}</p>
                                    </div>
                                    <p>{{ comment.content }}</p>
                                    <div class="pad-ver">
                                        <span class="tag tag-sm"><i class="fa fa-heart text-danger"></i> {{ comment.vote_up }} </span>
                                        <div class="btn-group">
                                            <button class="btn btn-sm btn-default btn-hover-success" ><i
                                                    class="fa fa-thumbs-up"></i></button>
                                            <button class="btn btn-sm btn-default btn-hover-danger"><i
                                                    class="fa fa-thumbs-down"></i></button>
                                        </div>
                                    </div>
                                    <hr>
                                </div>
                            {% endfor %}
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

{% endblock content %}

{% block javascript %}
<script type="text/javascript" src="https://www.shieldui.com/shared/components/latest/js/shieldui-all.min.js"></script>

<script type="text/javascript">
	jQuery(function ($) {
		$(".tabs_div").shieldTabs();
	});
</script>

{% endblock javascript %}

product/templates/product/base_productList.html
{% extends 'product/base.html' %}

{% load static %}

{% block title %}Product | {% endblock title %}
{% block header %}
<link type="text/css" rel="stylesheet" href="{% static 'product/css/listProduct.css' %}">
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<meta property='og:type' content="website" />
<meta property='og:url' itemprop="url" content="https://www.beautifme.com/product/" />
<meta name="description" content="List of products might be suitable for your skincare routine - beautifME skincare." />

<link rel="canonical" href="https://www.beautifme.com/product/" />
{% endblock header %}

{% block content %}
<ul class="breadcrumb">
    <li><a href="{% url 'homepage' %}">Home</a></li>
    <li><a href="{% url 'product:product-list' %}">Products</a></li>
</ul>


<div class="container">
    <h1 class="h1">Products</h1>
    <hr />
    {% if page_obj %}
    <div class="row">
        {% for product in page_obj %}
            <div class="col-md-3 col-sm-6" style="position:unset;">
                <a href="/product/{{ product.id }}/{{ product.slug }}/">
                    <div class="product-grid6">
                        <div class="product-image6">
                            <img class="pic-1 lazyload" src="{{ product.product_img.url }}" alt="{{ product.product_name}}-{{ product.brand.branding_name}}-beautifme" />
                        </div>
                        <div class="product-content">
                            <h3 class="title">{{ product.product_name }}</h3>
                            <div class="price">${{ product.price }}</div>
                        </div>
                        <ul class="social">
                        </ul>
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
    {% else %}
    <div class="row">
        <p>Uh oh, we haven't update any products at the moment, please come back later for more updates.</p>
    </div>
    {% endif %}
</div>

<div class="productPagination">
    <span>
        {% if page_obj.has_previous %}
        <a href="?page=1" class="space">&laquo; First</a>
        <a href="?page={{ page_obj.previous_page_number }}" class="space">Previous</a>
        {% endif %}
    </span>
    <span>
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
    </span>
    <span>
        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}" class="space">Next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}" class="space">Last &raquo;   </a>
        {% endif %}
    </span>
</div>
{% endblock content %}

product/templates/product/base_recommend.html
{% extends 'product/base.html' %}

{% load static %}

{% block title %}Recommend | {% endblock title %}
{% block header %}
    <link type="text/css" rel="stylesheet" href="{% static 'product/css/recommend.css' %}">
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <meta property='og:url' itemprop="url" content="https://www.beautifme.com/recommend/" />
    <meta name="description" content="Recommend you a perfect skincare routine with your skin condition - beautifME" />
    <meta name="keywords" content="Recommend skincare routine, skincare routine, routine for beginners"/>
    <meta name="keywords" content="Gợi ý chu trình dưỡng da, chu trình dưỡng da, chăm sóc da, chăm sóc da cho người mới bắt đầu"/>

    <link rel="canonical" href="https://www.beautifme.com/recommend/" />
    
{% endblock header %}

{% block content %}
<h1 style="display:none; width: 0px; height: 0px;" >Recommend</h1>
<div class="formRecommend">
    <div class="recommend-content">
        <div class="recommend-form">

            <form method="GET">
                <div class="form-group">
                    <p>{{ filterForm.form.as_p }}</p>
                </div>
                <!-- Button Recommend -->
                <input type="submit" class="submitButton" value="Recommend"/>
            </form>

        </div>
    </div>
</div>

<div class="container">
    <div class="timeline">
        {% if removerQ %}
        {# Makeup Remover List #}
        <div class="timeline-section">
            <div class="timeline-date">
                Makeup Remover
            </div>
            <div class="row">
                {% for remover in removerQ|slice:"4" %}
                <div class="col-md-3 col-sm-6">
                    <a href="/product/{{ remover.id }}/{{ remover.slug }}/">
                        <div class="product-grid6">
                            <div class="product-image6">

                                <img class="pic-1 lazyload" src="{{ remover.product_img.url }}" />

                            </div>
                            <div class="product-content">
                                <h3 class="title">{{ remover.product_name }}</h3>
                                <div class="price">
                                    ${{ remover.price }}
                                </div>
                            </div>
                            <ul class="social"></ul>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}

        {% if cleanserQ %}
        {# Cleanser List #}
        <div class="timeline-section">
            <div class="timeline-date">
                Cleanser
            </div>
            <div class="row">
                {% for cleanser in cleanserQ|slice:"4" %}
                <div class="col-md-3 col-sm-6">
                    <a href="/product/{{ cleanser.id }}/{{ cleanser.slug }}/">
                        <div class="product-grid6">
                            <div class="product-image6">
                                <img class="pic-1 lazyload" src="{{ cleanser.product_img.url }}" />
                            </div>
                            <div class="product-content">
                                <h3 class="title">{{ cleanser.product_name }}</h3>
                                <div class="price">
                                    ${{ cleanser.price }}
                                </div>
                            </div>
                            <ul class="social">
                            </ul>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}

        {% if lotionQ %}
        {# Lotion List #}
        <div class="timeline-section">
            <div class="timeline-date">
                Lotion
            </div>
            <div class="row">
                {% for lotion in lotionQ|slice:"4" %}
                <div class="col-md-3 col-sm-6">
                    <a href="/product/{{ lotion.id }}/{{ lotion.slug }}/">
                        <div class="product-grid6">
                            <div class="product-image6">

                                <img class="pic-1 lazyload" src="{{ lotion.product_img.url }}" />

                            </div>
                            <div class="product-content">
                                <h3 class="title">{{ lotion.product_name }}</h3>
                                <div class="price">
                                    ${{ lotion.price }}
                                </div>
                            </div>
                            <ul class="social"></ul>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}

        {% if moistQ %}
        {# Moisturizer List #}
        <div class="timeline-section">
            <div class="timeline-date">
                Moisturizer
            </div>
            <div class="row">
                {% for moist in moistQ|slice:"4" %}
                <div class="col-md-3 col-sm-6">
                    <a href="/product/{{ moist.id }}/{{ moist.slug }}/">
                        <div class="product-grid6">
                            <div class="product-image6">

                                <img class="pic-1 lazyload" src="{{ moist.product_img.url }}" />

                            </div>
                            <div class="product-content">
                                <h3 class="title">{{ moist.product_name }}</h3>
                                <div class="price">
                                    ${{ moist.price }}
                                </div>
                            </div>
                            <ul class="social"></ul>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}

        {% if sunscreenQ %}
        {# Sunscreen List #}
        <div class="timeline-section">
            <div class="timeline-date">
                Sunscreen
            </div>
            <div class="row">
                {% for sunscreen in sunscreenQ|slice:"4" %}

                <div class="col-md-3 col-sm-6">
                    <a href="/product/{{ sunscreen.id }}/{{ sunscreen.slug }}/">
                        <div class="product-grid6">
                            <div class="product-image6">
                                <img class="pic-1 lazyload" src="{{ sunscreen.product_img.url }}" />
                            </div>
                            <div class="product-content">
                                <h3 class="title">{{ sunscreen.product_name }}</h3>
                                <div class="price">
                                    ${{ sunscreen.price }}
                                </div>
                            </div>
                            <ul class="social"></ul>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}

    </div>
</div>
{% endblock content %}