IE104_SC/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.generic.base import TemplateView
import product.views as productV, news.views as newsV, accounts.views as accountV
import brand.views as Brand

# Media and Ckeditor
from django.conf.urls.static import static
from IE104_SC import settings
import os

from django.contrib.auth import views as authV

from django.contrib.sitemaps.views import sitemap
from sitemaps import ProductSitemap, NewsSitemap, StaticSitemap

# Rich Text Field

# Sitemaps
from django.contrib.sitemaps.views import sitemap
from django.contrib.sitemaps import views
from django.views.decorators.cache import cache_page


sitemaps = {
    'product': ProductSitemap,
    'news': NewsSitemap,
    'static': StaticSitemap,
}


urlpatterns = [
    path('', productV.Homepage, name='homepage'),
    path('admin/', admin.site.urls),
    path('product/', include('product.urls')), 
    path('news/', include('news.urls')),
    path('brand/', include('brand.urls')),

    # Authentication
    path('accounts/', include('django.contrib.auth.urls')),
    path('account/', include('accounts.urls')),
    # path('logout/', accountV.LogoutView.as_view(template_name="accounts/logout.html"), name='logout'),
    path('register/', accountV.registration, name='register'),
    path('login/', authV.LoginView.as_view(template_name="accounts/login.html"), name='login'),
    path('change_password/',accountV.change_password, name='change_password'),

    # Others
    path('search/', productV.SearchResults.as_view(), name='search_results'),
    path('recommend/', productV.Recommend, name='recommend'),
    path('about/', accountV.aboutView, name='about'),

    # rich text field
    path('djrichtextfield/', include('djrichtextfield.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),

    # sitemap
    path('sitemap.xml', views.index, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('site-<section>.xml', views.sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path("robots.txt", TemplateView.as_view(template_name="accounts/robots.txt", content_type="text/plain")),

    re_path('djga/', include('google_analytics.urls')),
]

# if settings.dev.DEBUG:
#     urlpatterns += [re_path('djga/', include('google_analytics.urls')),]

# if settings.DEBUG:
#    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# urlpatterns += static(settings.base.MEDIA_URL, document_root=settings.base.MEDIA_ROOT)

brand/urls.py
from django.urls import path
from . import views
import product.views as ProductV

app_name = 'brand'

urlpatterns = [
    path('', views.BrandList.as_view(), name='brand-list'),
    path('<int:brand_id>/<slug:slug>/', views.BrandPList, name='brandp-list'),
]

news/urls.py
from django.urls import path
from .views import NewsListView, NewsDetail

app_name = 'news'

urlpatterns = [
    path('', NewsListView.as_view(), name='news-list'),
    path('<int:news_id>/<str:slug>/', NewsDetail, name='news-detail')   
]

brand/models.py
from django.db import models
from django.template.defaultfilters import slugify

from multiselectfield import MultiSelectField

# Create your models here.
class Brand(models.Model):
    # branding_name = models.CharField(max_length=3, choices=BRANDING)
    branding_name = models.CharField(max_length=255, unique=True)

    brandImage = models.ImageField(upload_to='brand/images/')

    #Branding Category: Trending, Highend, Drugstore
    BRAND_CAT = [
        ('TREN', 'On Trending'), 
        ('HIGH', 'High-end Products'),
        ('DRUG', 'Drugstore Products'),
    ]

    # brand_cat = models.CharField(max_length=4, choices=BRAND_CAT, null=True, blank=True)
    brandCategory = MultiSelectField(choices=BRAND_CAT, null=True, blank=True)

    brandDescript = models.TextField()

    #slugField for brandname endpoint
    slug = models.SlugField(max_length=30, unique=True)

    def __str__(self):
        return self.branding_name

    def slug(self):
        return slugify(self.branding_name)

brand/views.py
from django.shortcuts import render

from django.views import generic

from .models import Brand
from product.models import Product

# Create your views here.
"""Print brand list"""
class BrandList(generic.ListView):
    model = Brand
    template_name = 'brand/base_brandList.html'
    context_object_name = 'brand_list'
    paginate_by = 12

    def get_queryset(self):
        brands = Brand.objects.order_by("branding_name")
        return brands
        
        
"""Print all product in xxx brand """
def BrandPList(request, brand_id, slug):
    brand = Brand.objects.get(pk=brand_id)
    products = Product.objects.all()
    productSelected = []
    for product in products:
        if product.brand_id == brand_id:
            productSelected.append(product)

    context = {
        'products': productSelected, 
         'brand': brand,
    }
    return render(request, 'brand/base_brandPList.html', context)

brand/templates/brand/base_brandList.html
{% extends 'product/base.html' %}

{% load static %}

{% block title %}Brand | {% endblock title %}
{% block header %}
<link type="text/css" rel="stylesheet" href="{% static 'brand/css/listBrand.css' %}">
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<!--Meta OpenGraph-->
<meta name="og:description" content="recommend skincare brand for beginners" />
<meta name="og:title" content="Brand | beautifME"/>
<meta name="og:url" content="https://www.beautifme.com/brand/"/>
<meta property='og:type' content="website" />
<!--Meta keywords-->
<meta name="keywords" content="recommend, skincare, skin care, skincare recommend, skincare recommend beautifme" />
<meta name="keywords"
    content="skincare routine for beginners, gợi ý chu trình chăm sóc da, gợi ý beautifme, dưỡng da beautifme" />
<meta name="keywords" content="dưỡng da cơ bản beautifme, dưỡng da, skincare for beginners" />
<meta name="keywords"
    content="oily, dry, combination, acne prone, normal skin, aging skin, 30s, 20s, wrinkle, anti-aging" />
<!--end Meta keywords-->
<meta charset="UTF-8" />
<meta name="description" content="Danh sách các thương hiệu chăm sóc da trên toàn thế giới - hãy chăm sóc làn da bạn cùng beautifME" />
<!--end Meta data-->
<link rel="canonical" href="https://www.beautifme.com/brand/" />
{% endblock header %}
{% block content %}

<ul class="breadcrumb">
    <li><a href="{% url 'homepage' %}">Home</a></li>
    <li><a href="{% url 'brand:brand-list' %}">Brand</a></li>
</ul>
<div class="container">
    <h1 class="h1">Brands </h1>
    <hr/>
    <div class="row">
        {% for brand in page_obj %}
            <!-- <li><a href="/product/{{ product.id }}">{{ product }}</a></li> -->
            <a href="/brand/{{ brand.id }}/{{ brand.slug }}/">
                <div class="col-md-3 col-sm-6" style="position:unset;">
                    <div class="product-grid6">
                        <div class="product-image6">
                            <img class="pic-1 lazyload"
                            src="{{ brand.brandImage.url }}" alt="{{ brand.branding_name }}-beautifme" />
                        </div>
                        <div class="product-content">
                            <h3 class="title"><a href="#">{{brand.branding_name }}</a></h3>   
                        </div>
                        <ul class="social">
                        </ul>
                    </div>
                </div>
            </a>
        {% endfor %}
    </div>
</div>

<div class="brandPagination">
    <span>
        {% if page_obj.has_previous %}
        <a href="?page=1" class="space">&laquo; First</a>
        <a href="?page={{ page_obj.previous_page_number }}" class="space">Previous</a>
        {% endif %}
    </span>
    <span>
        Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
    </span>
    <span>
        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}" class="space">Next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}" class="space">Last &raquo;</a>
    {% endif %}
    </span>
</div>
{% endblock content %}

brand/templates/brand/base_brandPList.html
{% extends 'product/base.html' %}

{% load static %}

{% block title %}{{ brand.branding_name }} | {% endblock title %}
{% block header %}
<link type="text/css" rel="stylesheet" href="{% static 'product/css/listProduct.css' %}">
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

<!--Meta data -->
<!--Meta OpenGraph-->
<meta name="og:description" content="{{ brand.brandDescript }}" />
<meta name="og:title" content="{{ brand }} | {{ brand.branding_name }}"/>
<meta name="og:url" content="https://www.beautifme.com/brand/{{ brand.id }}/{{ brand.slug }}/"/>
<meta name="og:type" content="website"/>
<meta name="og:img" content="{{ brand.brandImg.url }}">
<!--Meta keywords-->
<meta name="keywords" content="recommend, skincare, skin care, skincare recommend, skincare recommend beautifme" />
<meta name="keywords"
    content="skincare routine for beginners, gợi ý chu trình chăm sóc da, gợi ý beautifme, dưỡng da beautifme" />
<meta name="keywords" content="dưỡng da cơ bản beautifme, dưỡng da, skincare for beginners" />
<meta name="keywords"
    content="oily, dry, combination, acne prone, normal skin, aging skin, 30s, 20s, wrinkle, anti-aging" />
<!--end Meta keywords-->
<meta name="description" content="{{ brand.brandDescript }}" />
<meta name="product_article_id" content="{{ brand.id }}" />
<meta charset="UTF-8" />

<link rel="canonical" href="https://www.beautifme.com/brand/{{ brand.id }}/{{ brand.slug }}/" />

<!--end Meta data-->
{% endblock header %}

{% block content %}
<ul class="breadcrumb">
    <li><a href="{% url 'homepage' %}">Home</a></li>
    <li><a href="{% url 'brand:brand-list' %}">Brand</a></li>
    <li>{{ brand.branding_name }}</li>
</ul>

<div class="container">
    <h1 class="h1">{{ brand.branding_name }} </h1>
    <hr />
    {% if products %}
    <div class="row">
        {% for product in products %}
        <!-- <li><a href="/product/{{ product.id }}">{{ product }}</a></li> -->

        <div class="col-md-3 col-sm-6" style="position:unset">
            <a href="/product/{{ product.id }}/{{ product.slug }}/">
                <div class="product-grid6">
                    <div class="product-image6">
                        <img class="pic-1 lazyload" src="{{ product.product_img.url }}" alt="{{ product.product_name }}-{{ product.brand.branding_name}}-beautifme" />
                    </div>
                    <div class="product-content">
                        <h3 class="title">{{ product.product_name }}</h3>
                        <div class="price">${{ product.price }}</div>
                    </div>
                    <ul class="social">

                    </ul>
                </div>
            </a>
        </div>

        {% endfor %}
    </div>
    {% else %}
    <div class="row">
        <p>There are no product in {{ brand.branding_name }} ヽ(・∀・)ﾉ</p>
    </div>
    {% endif %}
</div>

{% endblock content %}